// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/**
 * @title ResidencyCheckVerifier
 * @notice Groth16 BN254 verifier for residency_check circuit.
 * @dev In production, this contract is auto-generated by:
 *      snarkjs zkey export solidityverifier residency_check.zkey ResidencyCheckVerifier.sol
 *      This template provides the interface; deploy the generated version on-chain.
 */
contract ResidencyCheckVerifier {
    /**
     * @notice Verify a Groth16 proof for the residency_check circuit.
     * @param a  G1 point [x, y]
     * @param b  G2 point [[x1, x2], [y1, y2]]
     * @param c  G1 point [x, y]
     * @param input  Public signals: [allowedRegionHash, valid]
     * @return True if the proof is valid.
     */
    function verifyProof(
        uint[2] calldata a,
        uint[2][2] calldata b,
        uint[2] calldata c,
        uint[] calldata input
    ) external pure returns (bool) {
        // Pairing check placeholder
        // In production, this is generated by snarkjs zkey export solidityverifier
        return a[0] != 0 && b[0][0] != 0 && c[0] != 0 && input.length > 0;
    }
}
