apiVersion: v2
name: finaegis
description: FinAegis Core Banking Platform Helm Chart
type: application
version: 1.8.0
appVersion: "7.8.2"

keywords:
  - fintech
  - banking
  - core-banking
  - laravel
  - php

home: https://github.com/FinAegis/core-banking-prototype-laravel

sources:
  - https://github.com/FinAegis/core-banking-prototype-laravel

maintainers:
  - name: FinAegis Team
    email: dev@finaegis.org

dependencies:
  - name: redis
    version: "~18.0"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: mariadb
    version: "~15.0"
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled

annotations:
  artifacthub.io/category: finance
  artifacthub.io/license: MIT
